In [1]:
import pandas as pd
import numpy as np

In [2]:
affiliations = pd.read_table("data/2016KDDCupSelectedAffiliations/2016KDDCupSelectedAffiliations.txt",names = ["id","university"])
affiliations.head()

         id                         university
0  0003B055            university of cambridge
1  0005FC5A          university at albany suny
2  000CF342            sungkyunkwan university
3  0011114D          university of east anglia
4  0011EAC4  university of southern california

In [3]:
selectedPapers = pd.read_table("data/2016KDDCupSelectedPapers/2016KDDCupSelectedPapers.txt",names = ["paperId","title","year","conferenceId","conferenceShortName"])
selectedPapers.head()

,paperId,title,year,conferenceId,conferenceShortName
0,7AB34E32,ADDiff: semantic differencing for activity dia...,2011,477F6C83,FSE
1,7BFD6C72,Boosting the performance of flow-sensitive poi...,2011,477F6C83,FSE
2,7DA0D7B5,BugCache for inspections: hit or miss?,2011,477F6C83,FSE
3,784EEC08,CSSL: a logic for specifying conditional scena...,2011,477F6C83,FSE
4,7A050622,Checking conformance of a producer and a consumer,2011,477F6C83,FSE

In [4]:
phase2ContestPapers = selectedPapers.loc[selectedPapers['conferenceShortName'].isin(["KDD","ICML"])]

In [5]:
phase2PaperIds = pd.unique(phase2ContestPapers.paperId.ravel())
phase2PaperIds[:20]

array(['7D3FA94E', '587E4D7F', '830E5ECD', '7D621AA2', '0C44B62A',
       '85E774CC', '7E0333E7', '8509C6A5', '8207F262', '835D675F',
       '84D97BA1', '5FC705BC', '820C61AC', '824E25DE', '130FDCB8',
       '840CA4D2', '8223BBD9', '5B5BB751', '824795EC', '8613408C'], dtype=object)

In [6]:
pafReader = pd.read_table("data/PaperAuthorAffiliations/PaperAuthorAffiliations.txt",chunksize=1000000,names = ["paperId","authorId","affiliationId","origAffilName","normAffilName","authorSeqNum"],dtype={"paperId":str,"authorId":str,"affiliationId":str,"origAffilName":str,"normAffilName":str,"authorSeqNum":np.int32})

In [31]:
chunk = pafReader.get_chunk()
phase2PaperAuths = chunk[chunk.paperId.isin(phase2PaperIds)]
print phase2PaperAuths.shape
for chunk in pafReader:
    p2pa = chunk[chunk.paperId.isin(phase2PaperIds)]
    phase2PaperAuths = pd.concat([phase2PaperAuths,p2pa])
    print phase2PaperAuths.shape

(92, 6)
(171, 6)
(283, 6)
(333, 6)
(461, 6)
(593, 6)
(722, 6)
(777, 6)
(803, 6)
(1027, 6)
(1065, 6)
(1325, 6)
(1343, 6)
(1533, 6)
(1575, 6)
(1653, 6)
(1794, 6)
(1835, 6)
(1875, 6)
(1974, 6)
(2103, 6)
(2159, 6)
(2201, 6)
(2210, 6)
(2244, 6)
(2365, 6)
(2501, 6)
(2651, 6)
(2869, 6)
(2883, 6)
(2883, 6)
(2883, 6)
(2885, 6)
(2885, 6)
(2885, 6)
(2887, 6)
(2887, 6)
(2887, 6)
(2888, 6)
(2889, 6)
(2890, 6)
(2892, 6)
(2892, 6)
(2893, 6)
(2894, 6)
(2896, 6)
(2897, 6)
(2899, 6)
(2900, 6)
(2900, 6)
(2902, 6)
(2904, 6)
(2904, 6)
(2904, 6)
(2904, 6)
(2904, 6)
(2904, 6)
(2906, 6)
(2907, 6)
(2907, 6)
(2909, 6)
(2910, 6)
(2910, 6)
(2910, 6)
(2910, 6)
(2910, 6)
(2912, 6)
(2914, 6)
(2916, 6)
(2917, 6)
(2918, 6)
(2920, 6)
(2920, 6)
(2920, 6)
(2920, 6)
(2921, 6)
(2922, 6)
(2922, 6)
(2923, 6)
(2924, 6)
(2928, 6)
(2929, 6)
(2929, 6)
(2930, 6)
(2930, 6)
(2930, 6)
(2931, 6)
(2931, 6)
(2931, 6)
(2933, 6)
(2934, 6)
(2936, 6)
(2936, 6)
(2940, 6)
(2940, 6)
(2940, 6)
(2941, 6)
(2941, 6)
(2942, 6)
(2942, 6)
(2943, 6)
(2944, 6)
(2944, 6)
(2944, 6)
(2944, 6)
(2947, 6)
(2948, 6)
(2949, 6)
(2952, 6)
(2952, 6)
(2953, 6)
(2953, 6)
(2953, 6)
(2954, 6)
(2954, 6)
(2957, 6)
(2958, 6)
(2959, 6)
(2959, 6)
(2960, 6)
(2961, 6)
(2961, 6)
(2961, 6)
(2961, 6)
(2961, 6)
(2962, 6)
(2963, 6)
(2964, 6)
(2965, 6)
(2966, 6)
(2970, 6)
(2972, 6)
(2974, 6)
(2975, 6)
(2976, 6)
(2976, 6)
(2976, 6)
(2976, 6)
(2976, 6)
(2976, 6)
(2978, 6)
(2981, 6)
(2981, 6)
(2981, 6)
(2981, 6)
(2983, 6)
(2984, 6)
(2984, 6)
(2987, 6)
(2988, 6)
(2988, 6)
(2989, 6)
(2990, 6)
(2991, 6)
(2992, 6)
(2994, 6)
(2996, 6)
(2997, 6)
(2997, 6)
(2998, 6)
(2999, 6)
(3000, 6)
(3001, 6)
(3002, 6)
(3005, 6)
(3005, 6)
(3006, 6)
(3007, 6)
(3009, 6)
(3009, 6)
(3012, 6)
(3015, 6)
(3019, 6)
(3019, 6)
(3019, 6)
(3019, 6)
(3019, 6)
(3020, 6)
(3021, 6)
(3022, 6)
(3024, 6)
(3029, 6)
(3031, 6)
(3032, 6)
(3033, 6)
(3034, 6)
(3034, 6)
(3034, 6)
(3035, 6)
(3036, 6)
(3036, 6)
(3036, 6)
(3036, 6)
(3036, 6)
(3037, 6)
(3038, 6)
(3039, 6)
(3039, 6)
(3040, 6)
(3040, 6)
(3041, 6)
(3042, 6)
(3042, 6)
(3046, 6)
(3047, 6)
(3050, 6)
(3050, 6)
(3051, 6)
(3052, 6)
(3054, 6)
(3057, 6)
(3058, 6)
(3061, 6)
(3062, 6)
(3064, 6)
(3064, 6)
(3066, 6)
(3067, 6)
(3068, 6)
(3068, 6)
(3071, 6)
(3072, 6)
(3076, 6)
(3077, 6)
(3080, 6)
(3080, 6)
(3080, 6)
(3080, 6)
(3084, 6)
(3085, 6)
(3087, 6)
(3087, 6)
(3089, 6)
(3090, 6)
(3090, 6)
(3091, 6)
(3092, 6)
(3093, 6)
(3096, 6)
(3096, 6)
(3096, 6)
(3098, 6)
(3099, 6)
(3102, 6)
(3103, 6)
(3104, 6)
(3104, 6)
(3104, 6)
(3104, 6)
(3106, 6)
(3106, 6)
(3106, 6)
(3107, 6)
(3107, 6)
(3109, 6)
(3111, 6)
(3111, 6)
(3111, 6)
(3112, 6)
(3113, 6)
(3114, 6)
(3114, 6)
(3116, 6)
(3116, 6)
(3117, 6)
(3119, 6)
(3122, 6)
(3124, 6)
(3127, 6)
(3128, 6)
(3129, 6)
(3129, 6)
(3129, 6)
(3131, 6)
(3131, 6)
(3131, 6)
(3135, 6)
(3137, 6)
(3137, 6)
(3137, 6)
(3140, 6)
(3141, 6)
(3142, 6)
(3144, 6)
(3145, 6)
(3145, 6)
(3148, 6)
(3148, 6)
(3148, 6)
(3148, 6)
(3148, 6)
(3148, 6)
(3148, 6)
(3148, 6)
(3150, 6)
(3154, 6)
(3154, 6)
(3154, 6)
(3154, 6)
(3156, 6)
(3156, 6)
(3156, 6)
(3237, 6)
(3446, 6)
(3839, 6)
(3913, 6)
(4072, 6)
(4112, 6)
(4146, 6)
(4555, 6)
(4693, 6)
(4754, 6)
(4869, 6)
(5146, 6)
(5227, 6)
(5297, 6)
(5416, 6)
(5466, 6)
(5551, 6)
(5620, 6)
(5691, 6)
(5736, 6)
(5773, 6)
(5795, 6)
(5821, 6)
(5838, 6)
(5916, 6)
(6002, 6)
(6022, 6)
(6114, 6)
(6147, 6)
(6158, 6)
(6271, 6)
(6341, 6)
(6362, 6)
(6364, 6)

In [ ]:
phase2PaperAuths.to_csv("data/phase2paperAuths2.csv")

In [6]:
phase2PaperAuths = pd.read_csv("data/phase2paperAuths2.csv")

In [141]:
paperAfill = phase2ContestPapers.merge(phase2PaperAuths)
paperAfill

,paperId,title,year,conferenceId,conferenceShortName,Unnamed: 0,authorId,affiliationId,origAffilName,normAffilName,authorSeqNum
0,7D3FA94E,A Co-training Approach for Multi-view Spectral...,2011,465F7C62,ICML,261385,7E143CB2,03FD8454,"Department of Computer Science, University of ...",university of maryland college park,1
1,7D3FA94E,A Co-training Approach for Multi-view Spectral...,2011,465F7C62,ICML,292499,47C4870E,03FD8454,"Department of Computer Science, University of ...",university of maryland college park,2
2,587E4D7F,A Coherent Interpretation of AUC as a Measure ...,2011,465F7C62,ICML,272766,6C239C48,0228E4F2,Department of Computer Science|||Intelligent S...,university of bristol,1
3,587E4D7F,A Coherent Interpretation of AUC as a Measure ...,2011,465F7C62,ICML,723074,127768C1,NaN,NaN,NaN,2
4,587E4D7F,A Coherent Interpretation of AUC as a Measure ...,2011,465F7C62,ICML,818657,81606936,NaN,Department of Computer Science,NaN,3
5,830E5ECD,A New Bayesian Rating System for Team Competit...,2011,465F7C62,ICML,418596,7954B168,NaN,"Steklov Mathematical Institute, 191023, nab. r...",NaN,1
6,830E5ECD,A New Bayesian Rating System for Team Competit...,2011,465F7C62,ICML,976056,80635B76,NaN,St. Petersburg Institute for Informatics and A...,NaN,2
7,7D621AA2,A Spectral Algorithm for Latent Tree Graphical...,2011,465F7C62,ICML,492282,7D1179C4,0477FFD3,"School of Computer Science, Carnegie Mellon Un...",carnegie mellon university,1
8,7D621AA2,A Spectral Algorithm for Latent Tree Graphical...,2011,465F7C62,ICML,524526,14EED946,0477FFD3,"School of Computer Science, Carnegie Mellon Un...",carnegie mellon university,3
9,7D621AA2,A Spectral Algorithm for Latent Tree Graphical...,2011,465F7C62,ICML,562322,7DFF1256,0477FFD3,"School of Computer Science, Carnegie Mellon Un...",carnegie mellon university,2
10,0C44B62A,A Three-Way Model for Collective Learning on M...,2011,465F7C62,ICML,256032,0A716934,4F076E00,"Siemens AG, Corporate Technology, Munich, Germany",siemens,2
11,0C44B62A,A Three-Way Model for Collective Learning on M...,2011,465F7C62,ICML,667924,804ECF93,NaN,"Ludwig-Maximilians-Universit?t, Munich, Germany",NaN,1
12,0C44B62A,A Three-Way Model for Collective Learning on M...,2011,465F7C62,ICML,4674,7263AD95,NaN,"Ludwig-Maximilians-Universit?t, Munich, Germany",NaN,3
13,85E774CC,A Unified Probabilistic Model for Global and L...,2011,465F7C62,ICML,926505,84698F4B,00C50601,"ECE Department, Northeastern University, Bosto...",northeastern university,1
14,85E774CC,A Unified Probabilistic Model for Global and L...,2011,465F7C62,ICML,932287,85781E34,00C50601,"ECE Department, Northeastern University, Bosto...",northeastern university,3
15,85E774CC,A Unified Probabilistic Model for Global and L...,2011,465F7C62,ICML,166360,7F8038BA,05B090CE,"EECS and Statistics Departments, University of...",university of california berkeley,2
16,7E0333E7,AOSO-LogitBoost: Adaptive One-Vs-One LogitBoos...,2011,465F7C62,ICML,440037,803F67EF,070DD774,"Research School of Computer Science, The Austr...",australian national university,3
17,7E0333E7,AOSO-LogitBoost: Adaptive One-Vs-One LogitBoos...,2011,465F7C62,ICML,952270,8222EC75,05E79D01,Tsinghua National Laboratory for Information S...,tsinghua university,1
18,7E0333E7,AOSO-LogitBoost: Adaptive One-Vs-One LogitBoos...,2011,465F7C62,ICML,963466,7E8739D7,05E79D01,Tsinghua National Laboratory for Information S...,tsinghua university,2
19,8509C6A5,Access to Unlabeled Data can Speed up Predicti...,2011,465F7C62,ICML,738218,2CC3EFA5,0C6703C3,"David R. Cheriton School of Computer Science, ...",david r cheriton school of computer science,1
20,8509C6A5,Access to Unlabeled Data can Speed up Predicti...,2011,465F7C62,ICML,738829,05827E54,0C6703C3,"David R. Cheriton School of Computer Science, ...",david r cheriton school of computer science,2
21,8509C6A5,Access to Unlabeled Data can Speed up Predicti...,2011,465F7C62,ICML,157323,54078239,0BC1D058,"School of Computer Science and Engineering, Th...",hebrew university of jerusalem,3
22,8207F262,Active Learning from Crowds,2011,465F7C62,ICML,932125,85781E34,00C50601,"ECE Department, Northeastern University, Bosto...",northeastern university,4
23,8207F262,Active Learning from Crowds,2011,465F7C62,ICML,976616,7EDDFA5D,00C50601,"ECE Department, Northeastern University, Bosto...",northeastern university,1
24,8207F262,Active Learning from Crowds,2011,465F7C62,ICML,799792,7EE50FCE,0734E3CC,"CAD and Knowledge Solutions, Siemens Healthcar...",siemens healthcare,2
25,8207F262,Active Learning from Crowds,2011,465F7C62,ICML,455562,855E1719,4F05DC4B,"Yahoo! Labs, Santa Clara, CA USA",yahoo,3
26,835D675F,Adaptive Kernel Approximation for Large-Scale ...,2011,465F7C62,ICML,786162,7A8E35D2,863BFDE1,Facebook,facebook,2
27,835D675F,Adaptive Kernel Approximation for Large-Scale ...,2011,465F7C62,ICML,550303,7D6A6150,0477FFD3,Carnegie Mellon University,carnegie mellon university,3
28,835D675F,Adaptive Kernel Approximation for Large-Scale ...,2011,465F7C62,ICML,550847,6E0DA203,0477FFD3,Carnegie Mellon University,carnegie mellon university,1
29,84D97BA1,Adaptively Learning the Crowd Kernel,2011,465F7C62,ICML,32271,718FD0E2,03376F29,Microsoft Research New England|||Weizmann Inst...,weizmann institute of science,1
...,...,...,...,...,...,...,...,...,...,...,...
6334,7762432D,Turn Waste into Wealth: On Simultaneous Cluste...,2015,436976F3,KDD,890457,7F0CCE58,05E79D01,"Tsinghua University, Beijing, China#TAB#",tsinghua university,3
6335,7762432D,Turn Waste into Wealth: On Simultaneous Cluste...,2015,436976F3,KDD,891493,8150412D,05E79D01,"Tsinghua University, Beijing, China#TAB#",tsinghua university,1
6336,78DAF807,Unified and Contrasting Cuts in Multiple Graph...,2015,436976F3,KDD,988076,8118A14E,01A8C383,"University of Michigan, Ann Arbor, Ann Arbor, ...",university of michigan,5
6337,78DAF807,Unified and Contrasting Cuts in Multiple Graph...,2015,436976F3,KDD,542883,80EFE91B,4CF99586,"Google, Mountain View, CA, USA#TAB#",google,2
6338,78DAF807,Unified and Contrasting Cuts in Multiple Graph...,2015,436976F3,KDD,257688,7F718ED7,050513B0,"University of California, Davis, Davis, CA, US...",university of california davis,6
6339,78DAF807,Unified and Contrasting Cuts in Multiple Graph...,2015,436976F3,KDD,260768,12915398,050513B0,"University of California, Davis, Davis, CA, US...",university of california davis,4
6340,78DAF807,Unified and Contrasting Cuts in Multiple Graph...,2015,436976F3,KDD,353145,7F585C69,4E3BBB83,"Naval Medical Research Center, Corpus Christi,...",naval medical research center,3
6341,7B91EEDB,Unsupervised Feature Selection with Adaptive S...,2015,436976F3,KDD,664318,7EF4802D,012E6F4E,"ISCAS, Beijing, China#TAB#",chinese academy of sciences,2
6342,7B91EEDB,Unsupervised Feature Selection with Adaptive S...,2015,436976F3,KDD,162749,7D3FCCAB,012E6F4E,"ISCAS, Beijing, China#TAB#",chinese academy of sciences,1
6343,7916A698,Using Local Spectral Methods to Robustify Grap...,2015,436976F3,KDD,927184,80143FAE,0D109F83,"Purdue University, West Lafayette, IN, USA#TAB#",purdue university,1
6344,7916A698,Using Local Spectral Methods to Robustify Grap...,2015,436976F3,KDD,162356,7D760E43,05B090CE,"University of California Berkeley, Berkeley, C...",university of california berkeley,2
6345,773BDF52,VEWS: A Wikipedia Vandal Early Warning System,2015,436976F3,KDD,243581,269AFF3B,03FD8454,"University of Maryland, College Park, MD, USA#...",university of maryland college park,3
6346,773BDF52,VEWS: A Wikipedia Vandal Early Warning System,2015,436976F3,KDD,283880,829B28FC,03FD8454,"University of Maryland, College Park, MD, USA#...",university of maryland college park,1
6347,773BDF52,VEWS: A Wikipedia Vandal Early Warning System,2015,436976F3,KDD,333979,835A947A,03FD8454,"University of Maryland, College Park, MD, USA#...",university of maryland college park,2
6348,761FC05D,Virus Propagation in Multiple Profile Networks,2015,436976F3,KDD,295089,7E26CDDA,0B317C57,"Ionian University, Corfu, Greece#TAB#",ionian university,2
6349,761FC05D,Virus Propagation in Multiple Profile Networks,2015,436976F3,KDD,179328,75BF1EF5,0A6C6FB4,"University of Patras, Patras, Greece#TAB#",university of patras,1
6350,761FC05D,Virus Propagation in Multiple Profile Networks,2015,436976F3,KDD,433263,0446DFBF,01461554,"Aristotle University of Thessaloniki, Thessalo...",aristotle university of thessaloniki,3
6351,761FC05D,Virus Propagation in Multiple Profile Networks,2015,436976F3,KDD,802656,80C8E931,36E22876,Technological Educational Institute of Western...,american hotel lodging educational institute,4
6352,77AB41CF,Warm Start for Parameter Selection of Linear C...,2015,436976F3,KDD,893539,7A7BD946,00FF56A8,"National Taiwan Univ., Taipei, Taiwan Roc#TAB#",national taiwan university,2
6353,77AB41CF,Warm Start for Parameter Selection of Linear C...,2015,436976F3,KDD,934261,7FA20DB4,00FF56A8,"National Taiwan Univ., Taipei, Taiwan Roc#TAB#",national taiwan university,3
6354,77AB41CF,Warm Start for Parameter Selection of Linear C...,2015,436976F3,KDD,989918,847A926F,00FF56A8,"National Taiwan Univ., Taipei, Taiwan Roc#TAB#",national taiwan university,1
6355,77AB41CF,Warm Start for Parameter Selection of Linear C...,2015,436976F3,KDD,14665,813BBDC8,00FF56A8,"National Taiwan Univ., Taipei, Taiwan Roc#TAB#",national taiwan university,5
6356,78C5253D,Website Optimization Problem and Its Solutions,2015,436976F3,KDD,607152,7D587B4F,04756336,"The University of Tokyo, Tokyo, Japan#TAB#",university of tokyo,2
6357,78C5253D,Website Optimization Problem and Its Solutions,2015,436976F3,KDD,669097,7A2D1297,04756336,"The University of Tokyo, Tokyo, Japan#TAB#",university of tokyo,1
6358,7B8FC80C,Who Supported Obama in 2012?: Ecological Infer...,2015,436976F3,KDD,499652,758EC809,0477FFD3,"Carnegie Mellon University, Pittsburgh, PA, US...",carnegie mellon university,3
6359,7B8FC80C,Who Supported Obama in 2012?: Ecological Infer...,2015,436976F3,KDD,534034,85043BFC,0477FFD3,"Carnegie Mellon University, Pittsburgh, PA, US...",carnegie mellon university,2
6360,7B8FC80C,Who Supported Obama in 2012?: Ecological Infer...,2015,436976F3,KDD,572561,7A38AC72,0477FFD3,"Carnegie Mellon University, Pittsburgh, PA, US...",carnegie mellon university,1
6361,79541ECF,Why It Happened: Identifying and Modeling the ...,2015,436976F3,KDD,161774,850E2B39,0A97E0C1,"The Chinese University of Hong Kong, Shatin, H...",the chinese university of hong kong,1
6362,79541ECF,Why It Happened: Identifying and Modeling the ...,2015,436976F3,KDD,182352,848E6C2C,0A97E0C1,"The Chinese University of Hong Kong, Shatin, H...",the chinese university of hong kong,3
6363,79541ECF,Why It Happened: Identifying and Modeling the ...,2015,436976F3,KDD,197900,80D9C0A8,0A97E0C1,"The Chinese University of Hong Kong, Shatin, H...",the chinese university of hong kong,2

In [8]:
paperAfill = paperAfill[pd.notnull(paperAfill['affiliationId'])]

In [9]:
kddPaperAffil = paperAfill.loc[paperAfill['conferenceShortName'].isin(["KDD"])]
icmlPaperAffil = paperAfill.loc[paperAfill['conferenceShortName'].isin(["ICML"])]

In [10]:
kddPaperAffil = kddPaperAffil[["affiliationId","paperId","year","authorId","normAffilName"]]
kddPaperAffil.head()

,affiliationId,paperId,year,authorId,normAffilName
3753,09988D7C,80438F9A,2011,5B4392E8,toyota technological institute at chicago
3754,09988D7C,80438F9A,2011,7C109C1A,toyota technological institute at chicago
3755,09988D7C,80438F9A,2011,5C10297F,toyota technological institute at chicago
3756,025F5CB1,7DEAB4D2,2011,84C0A52B,pierre and marie curie university
3757,025F5CB1,7DEAB4D2,2011,0743E5FB,pierre and marie curie university

In [11]:
kdd2011 = kddPaperAffil[kddPaperAffil["year"]==2011]
kdd2012 = kddPaperAffil[kddPaperAffil["year"]==2012]
kdd2013 = kddPaperAffil[kddPaperAffil["year"]==2013]
kdd2014 = kddPaperAffil[kddPaperAffil["year"]==2014]
kdd2015 = kddPaperAffil[kddPaperAffil["year"]==2015]

In [12]:
kdd2011

,affiliationId,paperId,year,authorId,normAffilName
3753,09988D7C,80438F9A,2011,5B4392E8,toyota technological institute at chicago
3754,09988D7C,80438F9A,2011,7C109C1A,toyota technological institute at chicago
3755,09988D7C,80438F9A,2011,5C10297F,toyota technological institute at chicago
3756,025F5CB1,7DEAB4D2,2011,84C0A52B,pierre and marie curie university
3757,025F5CB1,7DEAB4D2,2011,0743E5FB,pierre and marie curie university
3758,36E5AE3D,7DEAB4D2,2011,84BF62C2,kxen inc
3759,36E5AE3D,7DEAB4D2,2011,810C6EAB,kxen inc
3763,054B33A5,7DEAB4D2,2011,7D330332,institut national des sciences appliquees de r...
3764,08A948CC,785A92C5,2011,799D801D,johns hopkins university
3765,03C3607B,785A92C5,2011,7DB3797C,university of cincinnati
3766,0352694C,79126BBA,2011,80D4045E,arizona state university
3767,0352694C,79126BBA,2011,8118A14E,arizona state university
3768,0352694C,79126BBA,2011,85447164,arizona state university
3769,0352694C,79126BBA,2011,7D0B19CE,arizona state university
3770,4FF45383,760F0DEF,2011,7DC410E1,ibm
3771,4FF45383,760F0DEF,2011,7624D72E,ibm
3772,4FF45383,760F0DEF,2011,7E35733F,ibm
3773,4FF45383,760F0DEF,2011,767FA6A1,ibm
3774,4F4B6B43,7B06CE87,2011,7D785BBB,mayo clinic
3775,4F4B6B43,7B06CE87,2011,7DDCAAB3,mayo clinic
3776,07C34834,7B06CE87,2011,85258DCC,university of minnesota
3777,0B185497,7570038D,2011,8053616D,lehigh university
3778,4F05DC4B,7570038D,2011,834AC204,yahoo
3779,4F05DC4B,7570038D,2011,032D4125,yahoo
3780,4F05DC4B,7570038D,2011,77FCCFC7,yahoo
3781,0A1AB335,8171D51B,2011,7E97B4A3,university of new mexico
3782,0A1AB335,8171D51B,2011,7E0DC078,university of new mexico
3783,0A1AB335,8171D51B,2011,7EDAC040,university of new mexico
3784,0A1AB335,8171D51B,2011,829227F7,university of new mexico
3785,06C2C7BC,8171D51B,2011,10A1D956,ecole normale superieure de lyon
...,...,...,...,...,...
4259,4F4B6B43,803F170F,2011,7D9FED66,mayo clinic
4260,4F4B6B43,803F170F,2011,7DDCAAB3,mayo clinic
4261,4F4B6B43,803F170F,2011,805934F7,mayo clinic
4262,4F4B6B43,803F170F,2011,7E0207F4,mayo clinic
4263,4F872588,791C890D,2011,7041AE19,at t labs
4264,4F872588,791C890D,2011,7691B66E,at t labs
4265,4F872588,791C890D,2011,1958CA75,at t labs
4266,4F872588,791C890D,2011,7F7F2CC8,at t labs
4267,081E3F30,773F37B6,2011,80CE393E,harvard university
4268,4F05DC4B,773F37B6,2011,769ECF96,yahoo
4269,4F05DC4B,773F37B6,2011,804BA692,yahoo
4270,4F05DC4B,773F37B6,2011,85BA2CF1,yahoo
4271,0BF77E37,7F434470,2011,8538C8B7,hong kong university of science and technology
4272,4CE6FC2D,7F434470,2011,7F80840A,microsoft
4273,4CE6FC2D,7F434470,2011,7DC8FC42,microsoft
4274,4CE6FC2D,7F434470,2011,7DAB7ADE,microsoft
4275,0C4400FF,7FC449DD,2011,7F0D1139,cornell university
4276,0C4400FF,7FC449DD,2011,7EA6E6DB,cornell university
4277,0C4400FF,7FC449DD,2011,8111A701,cornell university
4278,05E79D01,7FC449DD,2011,80A0A7C8,tsinghua university
4279,4CE6FC2D,7FC449DD,2011,7D7F3D09,microsoft
4280,4CE6FC2D,7FC449DD,2011,7FEA4B7C,microsoft
4281,0554A5A7,7B6313E6,2011,7B6635CB,community supported agriculture
4282,4F05DC4B,7B6313E6,2011,7DBCFC31,yahoo
4283,4F05DC4B,7B6313E6,2011,7F7AEAC1,yahoo
4284,4F05DC4B,7B6313E6,2011,03FA5E44,yahoo
4285,4CE6FC2D,7B6313E6,2011,7BF4C916,microsoft
4286,067461C8,7ABBFFC8,2011,7556C0B0,university of pisa
4287,067461C8,7ABBFFC8,2011,85A0B858,university of pisa
4288,0262EA12,7ABBFFC8,2011,84EB8E30,institute for advanced study

In [13]:
kdd2011AuthorCount = kdd2011.groupby(["affiliationId"]).count()
kdd2011AuthorCount.head()

               paperId  year  authorId  normAffilName
affiliationId
0003B055             3     3         3              3
0011EAC4             3     3         3              3
004B1FBC             3     3         3              3
004E3300             2     2         2              2
007D2F41             1     1         1              1

In [14]:
kdd2011NoDupes = kdd2011[["affiliationId","paperId"]].drop_duplicates()

In [15]:
kdd2011PaperCount = kdd2011NoDupes.groupby(["affiliationId"]).count()
kdd2011PaperCount.head()

               paperId
affiliationId
0003B055             1
0011EAC4             3
004B1FBC             1
004E3300             1
007D2F41             1

In [16]:
kdd2011Index = kdd2011AuthorCount.index.astype(str)

In [17]:
kdd2011ACV = kdd2011AuthorCount["paperId"].values

In [18]:
kdd2011PCV = kdd2011PaperCount["paperId"].values

In [19]:
kdd2011PaperAuthorPair = [[]]
for i in range (0,kdd2011PCV.size):
    kdd2011PaperAuthorPair.append([kdd2011Index[i], kdd2011ACV[i],kdd2011PCV[i]])
kdd2011PaperAuthorPair
kdd2011PaperAuthorPair.remove([])

In [20]:
kdd2011Dataset = pd.DataFrame(kdd2011PaperAuthorPair,columns=["affiliationId","2011Authors","2011Papers"])
kdd2011Dataset.head()

  affiliationId  2011Authors  2011Papers
0      0003B055            3           1
1      0011EAC4            3           3
2      004B1FBC            3           1
3      004E3300            2           1
4      007D2F41            1           1

In [21]:
kdd2012AuthorCount = kdd2012.groupby(["affiliationId"]).count()
kdd2012NoDupes = kdd2012[["affiliationId","paperId"]].drop_duplicates()
kdd2012PaperCount = kdd2012NoDupes.groupby(["affiliationId"]).count()
kdd2012Index = kdd2012AuthorCount.index.astype(str)
kdd2012ACV = kdd2012AuthorCount["paperId"].values
kdd2012PCV = kdd2012PaperCount["paperId"].values
kdd2012PaperAuthorPair = [[]]
for i in range (0,kdd2012PCV.size):
    kdd2012PaperAuthorPair.append([kdd2012Index[i], kdd2012ACV[i],kdd2012PCV[i]])
kdd2012PaperAuthorPair.remove([])
kdd2012Dataset = pd.DataFrame(kdd2012PaperAuthorPair,columns=["affiliationId","2012Authors","2012Papers"])
kdd2012Dataset.head()

  affiliationId  2012Authors  2012Papers
0      0011114D            4           1
1      004B1FBC            5           2
2      007D2F41            4           1
3      00A52A7E            1           1
4      00F9B76E            2           1

In [27]:
KddAllYearDataset = pd.merge(kdd2011Dataset, kdd2012Dataset,how="outer", on=["affiliationId"])

In [24]:
kdd2013AuthorCount = kdd2013.groupby(["affiliationId"]).count()
kdd2013NoDupes = kdd2013[["affiliationId","paperId"]].drop_duplicates()
kdd2013PaperCount = kdd2013NoDupes.groupby(["affiliationId"]).count()
kdd2013Index = kdd2013AuthorCount.index.astype(str)
kdd2013ACV = kdd2013AuthorCount["paperId"].values
kdd2013PCV = kdd2013PaperCount["paperId"].values
kdd2013PaperAuthorPair = [[]]
for i in range (0,kdd2013PCV.size):
    kdd2013PaperAuthorPair.append([kdd2013Index[i], kdd2013ACV[i],kdd2013PCV[i]])
kdd2013PaperAuthorPair.remove([])
kdd2013Dataset = pd.DataFrame(kdd2013PaperAuthorPair,columns=["affiliationId","2013Authors","2013Papers"])
kdd2013Dataset.head()

  affiliationId  2013Authors  2013Papers
0      0003B055            9           3
1      0011EAC4            2           1
2      004B1FBC            2           1
3      007D2F41            2           1
4      009779A9            3           3

In [28]:
KddAllYearDataset = pd.merge(KddAllYearDataset, kdd2013Dataset,how="outer", on=["affiliationId"])
KddAllYearDataset

,affiliationId,2011Authors,2011Papers,2012Authors,2012Papers,2013Authors,2013Papers
0,0003B055,3,1,NaN,NaN,9,3
1,0011EAC4,3,3,NaN,NaN,2,1
2,004B1FBC,3,1,5,2,2,1
3,004E3300,2,1,NaN,NaN,NaN,NaN
4,007D2F41,1,1,4,1,2,1
5,0092C1B8,1,1,NaN,NaN,NaN,NaN
6,00A3C9C2,3,1,NaN,NaN,NaN,NaN
7,00C50601,3,1,NaN,NaN,2,2
8,00CE2969,1,1,NaN,NaN,NaN,NaN
9,00FA1C18,2,1,1,1,NaN,NaN
10,00FF56A8,4,2,3,2,8,2
11,01124466,3,1,1,1,1,1
12,0112E226,1,1,NaN,NaN,1,1
13,012C9CDF,5,2,2,1,NaN,NaN
14,012E6F4E,4,1,NaN,NaN,1,1
15,01328BF3,4,2,NaN,NaN,NaN,NaN
16,0134B592,3,1,3,1,6,3
17,01A17328,3,1,NaN,NaN,NaN,NaN
18,01A8C383,2,2,NaN,NaN,2,2
19,0228E4F2,5,2,NaN,NaN,NaN,NaN
20,0229448F,1,1,NaN,NaN,NaN,NaN
21,0259891E,13,7,14,6,14,5
22,025F5CB1,2,1,NaN,NaN,NaN,NaN
23,0262EA12,1,1,NaN,NaN,NaN,NaN
24,026778A2,2,2,2,1,4,1
25,0267A61E,2,2,NaN,NaN,NaN,NaN
26,02AD1047,1,1,NaN,NaN,NaN,NaN
27,02B09E25,2,1,NaN,NaN,NaN,NaN
28,02D828C1,1,1,NaN,NaN,NaN,NaN
29,031C31BE,6,2,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
194,03496C27,NaN,NaN,NaN,NaN,1,1
195,03839B48,NaN,NaN,NaN,NaN,2,1
196,03D00B37,NaN,NaN,NaN,NaN,2,1
197,0463457B,NaN,NaN,NaN,NaN,1,1
198,04AF010A,NaN,NaN,NaN,NaN,1,1
199,04B5445A,NaN,NaN,NaN,NaN,1,1
200,04BEE6D7,NaN,NaN,NaN,NaN,3,1
201,04F0A8A0,NaN,NaN,NaN,NaN,1,1
202,06041575,NaN,NaN,NaN,NaN,2,1
203,0653F611,NaN,NaN,NaN,NaN,2,1
204,06771A5A,NaN,NaN,NaN,NaN,1,1
205,07930A8B,NaN,NaN,NaN,NaN,1,1
206,0815134D,NaN,NaN,NaN,NaN,1,1
207,085ADB71,NaN,NaN,NaN,NaN,2,1
208,093456D7,NaN,NaN,NaN,NaN,4,1
209,099D876D,NaN,NaN,NaN,NaN,2,2
210,09DC92C5,NaN,NaN,NaN,NaN,3,1
211,09EA1A37,NaN,NaN,NaN,NaN,1,1
212,0B86525A,NaN,NaN,NaN,NaN,1,1
213,0C2C9DD2,NaN,NaN,NaN,NaN,7,2
214,0C2FE58D,NaN,NaN,NaN,NaN,2,1
215,0C34AB7F,NaN,NaN,NaN,NaN,1,1
216,0C601A7F,NaN,NaN,NaN,NaN,2,1
217,335ED749,NaN,NaN,NaN,NaN,2,1
218,34DF872C,NaN,NaN,NaN,NaN,1,1
219,4CC89935,NaN,NaN,NaN,NaN,1,1
220,4CDD5BAE,NaN,NaN,NaN,NaN,1,1
221,4DFEDD28,NaN,NaN,NaN,NaN,1,1
222,4E2EC568,NaN,NaN,NaN,NaN,1,1
223,862ADA3F,NaN,NaN,NaN,NaN,7,4

In [29]:
kdd2014AuthorCount = kdd2014.groupby(["affiliationId"]).count()
kdd2014NoDupes = kdd2014[["affiliationId","paperId"]].drop_duplicates()
kdd2014PaperCount = kdd2014NoDupes.groupby(["affiliationId"]).count()
kdd2014Index = kdd2014AuthorCount.index.astype(str)
kdd2014ACV = kdd2014AuthorCount["paperId"].values
kdd2014PCV = kdd2014PaperCount["paperId"].values
kdd2014PaperAuthorPair = [[]]
for i in range (0,kdd2014PCV.size):
    kdd2014PaperAuthorPair.append([kdd2014Index[i], kdd2014ACV[i],kdd2014PCV[i]])
kdd2014PaperAuthorPair.remove([])
kdd2014Dataset = pd.DataFrame(kdd2014PaperAuthorPair,columns=["affiliationId","2014Authors","2014Papers"])
kdd2014Dataset.head()

  affiliationId  2014Authors  2014Papers
0      0005FC5A            1           1
1      0011EAC4           17           7
2      00243975            1           1
3      00493E54            1           1
4      004E3300            1           1

In [31]:
KddAllYearDataset4 = pd.merge(KddAllYearDataset, kdd2014Dataset,how="outer", on=["affiliationId"])
KddAllYearDataset4

,affiliationId,2011Authors,2011Papers,2012Authors,2012Papers,2013Authors,2013Papers,2014Authors,2014Papers
0,0003B055,3,1,NaN,NaN,9,3,NaN,NaN
1,0011EAC4,3,3,NaN,NaN,2,1,17,7
2,004B1FBC,3,1,5,2,2,1,NaN,NaN
3,004E3300,2,1,NaN,NaN,NaN,NaN,1,1
4,007D2F41,1,1,4,1,2,1,12,3
5,0092C1B8,1,1,NaN,NaN,NaN,NaN,NaN,NaN
6,00A3C9C2,3,1,NaN,NaN,NaN,NaN,NaN,NaN
7,00C50601,3,1,NaN,NaN,2,2,5,2
8,00CE2969,1,1,NaN,NaN,NaN,NaN,NaN,NaN
9,00FA1C18,2,1,1,1,NaN,NaN,NaN,NaN
10,00FF56A8,4,2,3,2,8,2,4,2
11,01124466,3,1,1,1,1,1,NaN,NaN
12,0112E226,1,1,NaN,NaN,1,1,2,1
13,012C9CDF,5,2,2,1,NaN,NaN,NaN,NaN
14,012E6F4E,4,1,NaN,NaN,1,1,2,1
15,01328BF3,4,2,NaN,NaN,NaN,NaN,1,1
16,0134B592,3,1,3,1,6,3,NaN,NaN
17,01A17328,3,1,NaN,NaN,NaN,NaN,NaN,NaN
18,01A8C383,2,2,NaN,NaN,2,2,5,3
19,0228E4F2,5,2,NaN,NaN,NaN,NaN,NaN,NaN
20,0229448F,1,1,NaN,NaN,NaN,NaN,NaN,NaN
21,0259891E,13,7,14,6,14,5,7,4
22,025F5CB1,2,1,NaN,NaN,NaN,NaN,NaN,NaN
23,0262EA12,1,1,NaN,NaN,NaN,NaN,NaN,NaN
24,026778A2,2,2,2,1,4,1,7,3
25,0267A61E,2,2,NaN,NaN,NaN,NaN,2,1
26,02AD1047,1,1,NaN,NaN,NaN,NaN,NaN,NaN
27,02B09E25,2,1,NaN,NaN,NaN,NaN,3,1
28,02D828C1,1,1,NaN,NaN,NaN,NaN,NaN,NaN
29,031C31BE,6,2,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
238,04C30B43,NaN,NaN,NaN,NaN,NaN,NaN,7,3
239,056EA0E2,NaN,NaN,NaN,NaN,NaN,NaN,1,1
240,0581F5D5,NaN,NaN,NaN,NaN,NaN,NaN,1,1
241,05B9651E,NaN,NaN,NaN,NaN,NaN,NaN,2,1
242,05DBF710,NaN,NaN,NaN,NaN,NaN,NaN,2,1
243,0616AB9C,NaN,NaN,NaN,NaN,NaN,NaN,2,2
244,0619822C,NaN,NaN,NaN,NaN,NaN,NaN,1,1
245,0661DECB,NaN,NaN,NaN,NaN,NaN,NaN,2,1
246,0699B629,NaN,NaN,NaN,NaN,NaN,NaN,1,1
247,070A58AF,NaN,NaN,NaN,NaN,NaN,NaN,3,2
248,070DD774,NaN,NaN,NaN,NaN,NaN,NaN,1,1
249,0749A315,NaN,NaN,NaN,NaN,NaN,NaN,2,1
250,07511464,NaN,NaN,NaN,NaN,NaN,NaN,3,1
251,07874D3C,NaN,NaN,NaN,NaN,NaN,NaN,1,1
252,07F8AFEC,NaN,NaN,NaN,NaN,NaN,NaN,1,1
253,080DBBEF,NaN,NaN,NaN,NaN,NaN,NaN,1,1
254,0877C406,NaN,NaN,NaN,NaN,NaN,NaN,1,1
255,08B22DAB,NaN,NaN,NaN,NaN,NaN,NaN,3,1
256,08D7E515,NaN,NaN,NaN,NaN,NaN,NaN,2,1
257,0948C934,NaN,NaN,NaN,NaN,NaN,NaN,4,1
258,09676E2E,NaN,NaN,NaN,NaN,NaN,NaN,2,1
259,09EB4F00,NaN,NaN,NaN,NaN,NaN,NaN,2,2
260,0AB1BE73,NaN,NaN,NaN,NaN,NaN,NaN,1,1
261,0B845BA3,NaN,NaN,NaN,NaN,NaN,NaN,1,1
262,0B908117,NaN,NaN,NaN,NaN,NaN,NaN,2,1
263,0D52D485,NaN,NaN,NaN,NaN,NaN,NaN,2,1
264,350410CF,NaN,NaN,NaN,NaN,NaN,NaN,3,2
265,35095641,NaN,NaN,NaN,NaN,NaN,NaN,1,1
266,4ECD74BC,NaN,NaN,NaN,NaN,NaN,NaN,1,1
267,86317390,NaN,NaN,NaN,NaN,NaN,NaN,3,2

In [32]:
kdd2015AuthorCount = kdd2015.groupby(["affiliationId"]).count()
kdd2015NoDupes = kdd2015[["affiliationId","paperId"]].drop_duplicates()
kdd2015PaperCount = kdd2015NoDupes.groupby(["affiliationId"]).count()
kdd2015Index = kdd2015AuthorCount.index.astype(str)
kdd2015ACV = kdd2015AuthorCount["paperId"].values
kdd2015PCV = kdd2015PaperCount["paperId"].values
kdd2015PaperAuthorPair = [[]]
for i in range (0,kdd2015PCV.size):
    kdd2015PaperAuthorPair.append([kdd2015Index[i], kdd2015ACV[i],kdd2015PCV[i]])
kdd2015PaperAuthorPair.remove([])
kdd2015Dataset = pd.DataFrame(kdd2015PaperAuthorPair,columns=["affiliationId","2015Authors","2015Papers"])
kdd2015Dataset.head()

  affiliationId  2015Authors  2015Papers
0      0005FC5A            1           1
1      0011EAC4            5           1
2      0045D019            1           1
3      009779A9            2           1
4      00BC8D07            1           1

In [33]:
KddAllYearDataset5 = pd.merge(KddAllYearDataset4, kdd2015Dataset,how="outer", on=["affiliationId"])
KddAllYearDataset5

,affiliationId,2011Authors,2011Papers,2012Authors,2012Papers,2013Authors,2013Papers,2014Authors,2014Papers,2015Authors,2015Papers
0,0003B055,3,1,NaN,NaN,9,3,NaN,NaN,NaN,NaN
1,0011EAC4,3,3,NaN,NaN,2,1,17,7,5,1
2,004B1FBC,3,1,5,2,2,1,NaN,NaN,NaN,NaN
3,004E3300,2,1,NaN,NaN,NaN,NaN,1,1,NaN,NaN
4,007D2F41,1,1,4,1,2,1,12,3,NaN,NaN
5,0092C1B8,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,00A3C9C2,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,00C50601,3,1,NaN,NaN,2,2,5,2,4,3
8,00CE2969,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,00FA1C18,2,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN
10,00FF56A8,4,2,3,2,8,2,4,2,12,5
11,01124466,3,1,1,1,1,1,NaN,NaN,3,1
12,0112E226,1,1,NaN,NaN,1,1,2,1,1,1
13,012C9CDF,5,2,2,1,NaN,NaN,NaN,NaN,NaN,NaN
14,012E6F4E,4,1,NaN,NaN,1,1,2,1,2,1
15,01328BF3,4,2,NaN,NaN,NaN,NaN,1,1,NaN,NaN
16,0134B592,3,1,3,1,6,3,NaN,NaN,4,3
17,01A17328,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,01A8C383,2,2,NaN,NaN,2,2,5,3,9,8
19,0228E4F2,5,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,0229448F,1,1,NaN,NaN,NaN,NaN,NaN,NaN,6,4
21,0259891E,13,7,14,6,14,5,7,4,4,3
22,025F5CB1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,0262EA12,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,026778A2,2,2,2,1,4,1,7,3,4,2
25,0267A61E,2,2,NaN,NaN,NaN,NaN,2,1,1,1
26,02AD1047,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,02B09E25,2,1,NaN,NaN,NaN,NaN,3,1,2,1
28,02D828C1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,031C31BE,6,2,NaN,NaN,NaN,NaN,NaN,NaN,2,1
...,...,...,...,...,...,...,...,...,...,...,...
294,08B9DFEF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
295,08F452CF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2
296,0947E863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1
297,09630970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1
298,09D7E4FA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,2
299,09DDAA88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
300,09EB15AA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
301,0A08EC51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,1
302,0A6C6FB4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
303,0B00BA67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,3
304,0B08755E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2
305,0B0DA3DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
306,0B317C57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
307,0B7D39A1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
308,0BC22D41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1
309,0BC3491B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
310,0C1EB600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1
311,0C2AE079,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
312,0CA4B187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
313,0DC52CFD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1
314,36E22876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
315,373A6845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
316,4CC3C85D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
317,4CD2C7C1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1
318,4D2B1EE6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
319,4D66E94F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2
320,4E3BBB83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
321,500B3463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
322,8623AC36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
323,8626355D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1

In [38]:
KddDatasetAffiliationList = KddAllYearDataset5["affiliationId"].values

In [40]:
KddDatasetFinal = KddAllYearDataset5.fillna(0)
KddDatasetFinal.head()

,affiliationId,2011Authors,2011Papers,2012Authors,2012Papers,2013Authors,2013Papers,2014Authors,2014Papers,2015Authors,2015Papers
0,0003B055,3,1,0,0,9,3,0,0,0,0
1,0011EAC4,3,3,0,0,2,1,17,7,5,1
2,004B1FBC,3,1,5,2,2,1,0,0,0,0
3,004E3300,2,1,0,0,0,0,1,1,0,0
4,007D2F41,1,1,4,1,2,1,12,3,0,0

In [58]:
import random
KddDatasetFinalValues = KddDatasetFinal.values
random.shuffle(KddDatasetFinalValues)
KddDatasetFinalValues

array([['0003B055', 3.0, 1.0, ..., 0.0, 0.0, 0.0],
       ['0011EAC4', 3.0, 3.0, ..., 7.0, 5.0, 1.0],
       ['0003B055', 3.0, 1.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['0DC52CFD', 0.0, 0.0, ..., 0.0, 2.0, 1.0],
       ['031C31BE', 6.0, 2.0, ..., 0.0, 2.0, 1.0],
       ['0C2C9DD2', 0.0, 0.0, ..., 1.0, 3.0, 2.0]], dtype=object)

In [74]:
KddDatasetIndex = KddDatasetFinalValues[:,0]

In [92]:
KddDataset_X = KddDatasetFinalValues[:,1:8]

In [93]:
KddDataset_X

array([[3.0, 1.0, 0.0, ..., 9.0, 3.0, 0.0],
       [3.0, 3.0, 0.0, ..., 2.0, 1.0, 17.0],
       [3.0, 1.0, 0.0, ..., 9.0, 3.0, 0.0],
       ...,
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [6.0, 2.0, 0.0, ..., 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, ..., 7.0, 2.0, 2.0]], dtype=object)

In [84]:
KddDataset_y = KddDatasetFinalValues[:,10]

In [75]:
KddX_train = KddDataset_X[:194]
KddY_train = KddDataset_y[:194]
KddX_test = KddDataset_X[194:]
KddY_test = KddDataset_y[194:]

In [94]:
from sklearn import linear_model
from sklearn import cross_validation
lr = linear_model.LinearRegression()
scores = cross_validation.cross_val_score(lr, KddDataset_X, KddDataset_y, cv=5)

In [95]:
scores

array([ 0.30767672,  0.71489838,  0.46354993,  0.7683091 ,  0.12391672])

In [111]:
KddDatasetPapersOnly_X = KddDatasetFinalValues[:,[2,4,6,8]]

In [112]:
scores = cross_validation.cross_val_score(lr, KddDatasetPapersOnly_X, KddDataset_y, cv=5)
scores

array([ 0.43868656,  0.74892098,  0.51245943,  0.80185429,  0.26135175])

In [113]:
scores.mean()

0.55265460267460276

In [114]:
KddDatasetAuthorsOnly_X = KddDatasetFinalValues[:,[1,3,5,7]]

In [115]:
scores = cross_validation.cross_val_score(lr, KddDatasetAuthorsOnly_X, KddDataset_y, cv=5)
scores

array([ 0.21120327,  0.66853282,  0.41636393,  0.78548085,  0.26047758])

In [116]:
scores.mean()

0.46841169222183299

In [130]:
submissionIndex = KddDatasetFinal["affiliationId"].values

In [122]:
KddDatasetFinal.head()

,affiliationId,2011Authors,2011Papers,2012Authors,2012Papers,2013Authors,2013Papers,2014Authors,2014Papers,2015Authors,2015Papers
0,0003B055,3,1,0,0,9,3,0,0,0,0
1,0011EAC4,3,3,0,0,2,1,17,7,5,1
2,004B1FBC,3,1,5,2,2,1,0,0,0,0
3,004E3300,2,1,0,0,0,0,1,1,0,0
4,007D2F41,1,1,4,1,2,1,12,3,0,0

In [132]:
submissionXTrain = KddDatasetFinal[["2011Papers","2012Papers","2013Papers","2014Papers"]].values

In [133]:
submissionYTrain = KddDatasetFinal["2015Papers"].values

In [134]:
lr.fit(submissionXTrain,submissionYTrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [137]:
submissionData = KddDatasetFinal[["2012Papers","2013Papers","2014Papers","2015Papers"]].values

In [139]:
probabilities = lr.predict(submissionData)

In [148]:
KddSubmission = [[]]
k= 0
for i in probabilities:
    KddSubmission.append(["436976F3",KddDatasetIndex[k],i])
    k = k+1
KddSubmission.remove([])

In [151]:
KddSubmissionDF = pd.DataFrame(KddSubmission, columns=["conferenceId","affiliationId","score"])

In [160]:
KddSubmissionDF.sort("score",ascending=False,inplace=True)

In [179]:
def probabilityConversion(x):
    if type(x) is str:
        return x
    else:
        return x/12.3299

In [180]:
KddSubmissionDF.head()

    conferenceId affiliationId      score
116     436976F3      07CB626B  12.329808
40      436976F3      0368E8BE  10.517039
127     436976F3      0B3B54E4   9.229984
32      436976F3      00FF56A8   9.016158
53      436976F3      00C50601   8.521582

In [182]:
KddSubmissionFinal = KddSubmissionDF.applymap(probabilityConversion)

In [188]:
KddSubmissionFinal.drop(KddSubmissionFinal.index[40:], inplace=True)

In [189]:
KddSubmissionFinal.to_csv("submissions/kddresults2.tsv",sep = "\t",index = False,header = False)